### PR TITLE
Redirect to homepage from registration page if the beta.open_registration flag is not set

### PR DESCRIPTION
**Pull request by afaikafk**
Provide means to disable the all-accessible registration page.

### CODE REVIEW

**Comment by foxbunny** [comment]
Isn't it simpler to just omit the request handler in the routes() fn depending on the config value?

**Comment by afaikafk** [comment]
It is, I just thought there might be a dedicated page added later for users trying to register this way.

**Comment by foxbunny** [comment]
For the first iteration, the goal is to implement closed beta only, so it's better if the route handler is not even there. Once we're out of closed beta, we'll replace the beta signup form with the standard join form or something along those lines.

**Comment by afaikafk** [comment]
ok

**Pull request merged**
